name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - 'release-**'

permissions:
  contents: write
  security-events: write
  pull-requests: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Extract short SHA
        id: short_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Determine Image Tag
        id: image-tag
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/development' ]]; then
            echo "tags=${{ secrets.DOCKERHUBUSERNAME }}/devops_app:development-${{ steps.short_sha.outputs.sha }}" >> "$GITHUB_OUTPUT"
          elif [[ ${{ github.ref }} == 'refs/heads/release-'* ]]; then
            VERSION=$(echo ${{ github.ref }} | cut -d '/' -f 3 | sed 's/release-//')
            echo "tags=${{ secrets.DOCKERHUBUSERNAME }}/devops_app:${VERSION}-${{ steps.short_sha.outputs.sha }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.image-tag.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.image-tag.outputs.tags }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'